// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }






import type { Metadata } from 'next';
import './globals.css';
// import SmoothScroll from '@/components/SmoothScroll';
import CustomCursor from '@/components/CustomCursor';
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: 'AD VENTURE — Creative & Production Company',
  description:
    'AD VENTURE is a modern creative and production company. We build impactful visual experiences through cinematic storytelling, branding, advertisements, VFX, AI creativity, and premium media production. From concept to final frame — engineered to be unforgettable.',
  keywords: [
    'creative production company', 'cinematic commercials', 'VFX production',
    'brand identity', 'AI creativity', 'motion graphics', 'digital storytelling',
    'luxury brand visuals', 'ad venture', 'advertisement agency',
    'Dubai production company', 'Mumbai production company',
  ],
  authors: [{ name: 'AD VENTURE Productions' }],
  openGraph: {
    title: 'AD VENTURE — We Build Cinematic Worlds.',
    description: 'Commercials, campaigns, VFX, AI creativity and brand storytelling engineered to be unforgettable.',
    siteName: 'AD VENTURE Productions',
    type: 'website',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AD VENTURE — We Build Cinematic Worlds.',
    description: 'Commercials, campaigns, VFX, AI creativity and brand storytelling engineered to be unforgettable.',
  },
  robots: { index: true, follow: true, googleBot: { index: true, follow: true } },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={cn("scroll-smooth", "font-sans", geist.variable)}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
      </head>
      <body className="bg-black text-white antialiased overflow-x-hidden">
        <CustomCursor />
        {/* <SmoothScroll> */}
          {children}
        {/* </SmoothScroll> */}
      </body>
    </html>
  );
}